apiVersion: v2
name: secrets
description: A self-hosted secrets manager with group sharing and API tokens
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - secrets
  - passwords
  - credentials
home: https://hub.docker.com/r/ruslanrwx/secrets
sources:
  - https://github.com/ruslanrwx/secrets
maintainers:
  - name: ruslanrwx
